### ISSUE TITLE
Couldn't Connect To Display

### ISSUE THREAD

**Issue by Queuecumber** [pubgeo/core3d-metrics#41]
We run the evaluation metrics on a cluster which is headless only (no GUI). and I am getting the following error when running the docker container

```
Traceback (most recent call last):
  File "/usr/local/bin/core3d-metrics", line 11, in <module>
    load_entry_point('core3dmetrics==0.0.0', 'console_scripts', 'core3d-metrics')()
  File "/usr/local/lib/python3.6/dist-packages/core3dmetrics/run_geometrics.py", line 345, in main
    run_geometrics(configfile=args.config,**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/core3dmetrics/run_geometrics.py", line 190, in run_geometrics
    plot.make(refDSM, 'Reference DSM', 111, colorbar=True, saveName="input_refDSM", badValue=noDataValue)
  File "/usr/local/lib/python3.6/dist-packages/core3dmetrics/geometrics/plot.py", line 65, in make
    plt.figure(fig)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 548, in figure
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py", line 1044, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2020, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "192.168.34.9:11.0"
```

I have attached the full output log as well

[error.log](https://github.com/pubgeo/core3d-metrics/files/2041880/error.log)

My ShowPlots options is set to false, SavePlots is true. If both are set to false, I don't get this error message

Is there a way to run the scorer in fully headless mode and still have plots?

**Comment by aleichtman** [comment]
Unsetting the DISPLAY environment variable on the cluster might do that trick.

**Comment by Queuecumber** [comment]
That worked, thanks
